#3. Crie um programa que leia 2 números e mostre a soma entre eles.
print('*' * 20)
print('C O N C A T E N A Ç Ã O')
print('*' * 20)
n1 = input('Digite o 1º Valor: ')
n2 = input('2º Valor: ')
print('A soma entre {} e {} vale {}'.format(n1, n2, (n1+n2)))
print('*' * 20)
print('S O M A')
print('*' * 20)
num1 = int(input('Digite o 1º valor: '))
num2 = int(input('2º Valor: '))
print('A soma entre {} e {} vale {}'.format(n1, n2, (num1+num2)))
